version: '3.8'

services:
  stm-localizacao-rs:
    image: ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    container_name: stm-localizacao-rs
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    env_file:
      - .env
    environment:
      - RESOURCE-SERVER-PORT=${RESOURCE_SERVER_PORT}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_H2_CONSOLE_ENABLED=${SPRING_H2_CONSOLE_ENABLED}
      - SPRING_H2_CONSOLE_WEB_ALLOW_OTHERS=${SPRING_H2_CONSOLE_WEB_ALLOW_OTHERS}
      - SPRING_JPA_HIBERNATE_DIALECT=${SPRING_JPA_HIBERNATE_DIALECT}
      - SPRING_JPA_SHOW_SQL=${SPRING_JPA_SHOW_SQL}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_SQL_INIT_MODE=${SPRING_SQL_INIT_MODE}
      - SWAGGER_ENABLED=${SWAGGER_ENABLED}
      - MONITORING_ENDPOINTS=${MONITORING_ENDPOINTS}
      - MONITORING_PROMETHEUS=${MONITORING_PROMETHEUS}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${CONTAINER_PORT}/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
